#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

node "scripts/generateHtml.mjs"

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

echo "$FILES" | xargs -I{} prettier --write --ignore-path .prettierignore --config .prettierrc {}
echo "$FILES" | xargs git add

exit 0
