#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

node "scripts/generateHtml.mjs"

# make prettier format all files except node_modules, .husky, .git, .gitignore, .prettierrc and yarn.lock
prettier --write --ignore-path .prettierignore --config .prettierrc "./**/*"
